### PR TITLE
fix: locals in inherited layout

### LINKED ISSUE #44: nested extends locals are not working
Hi, i'm trying to use locals with nested extends block, but it's not working. This use case is interesting for posthtml-extend to create components from code snippets and use them into bigger pages.
```
<!-- parent.html -->
<div>
    <block name="content"></block>
</div>
```
```
<!-- nested.html -->
<div class="nested">
    <span>{{ nested_var }}</span>
    <block name="nested"></block>
</div>
```
```
<!-- page.html -->
<extends src="parent.html">
  <block name="content">
        <extends src="nested.html" locals='{"nested_var":"tada!"}'>
          <block name="nested">nested content example</block>
        </extends>
  </block>
</extends>
```
results in (code is reformatted for readability):
```
<div class="parent">
    <div class="nested">
        <span>undefined</span>
        nested content example
    </div>        
</div>
```

### PR DESCRIPTION
**Pull request by nelsonihc**
Hi, this fixes the use case described in #44 

I appreciate your feedback in this regard!

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -47,12 +47,13 @@ function handleExtendsNodes(tree, options, messages) {
         locals = JSON.parse(extendsNode.attrs.locals);
       } catch {}
     }
-    options.expressions.locals = merge(options.expressions.locals, locals);
-    options.plugins.push(expressions(options.expressions));
+
+    var options_expressions = merge(options.expressions, {locals});
```
Comment (Scrum) [inline src/index.js]: 1. Not very clear about the purpose of just such a merger?
This will cost more than the current merger
2. var ?

File: src/index.js [hunk 2]
```diff
@@ -47,12 +47,13 @@ function handleExtendsNodes(tree, options, messages) {
...
+    var plugins = [...options.plugins, expressions(options_expressions)];
```
Comment (Scrum) [inline src/index.js]: 1. var ?

**Review by Scrum — CHANGES_REQUESTED** [review]

File: src/index.js (hunk 1 above)
Comment (nelsonihc) [reply src/index.js]: the merge is really suboptimal, and after testing it was proven unecessary. the new variable is not needed.

File: src/index.js (hunk 2 above)
Comment (nelsonihc) [reply src/index.js]: 😊 sorry, I've no experience in JS, I've educaded myself a little more on scoping. fixed.

**Review by Scrum — APPROVED** [review]
